import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]";
import Login from "./Login";
import Header from "./Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);
  console.log({session})
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="">
        {!session && (
          <div><Login/></div>
        )}
        {session && (
          <>
          <div className="max-w-lg mx-auto">
            <Header/>
           {children}
           </div>
          </>
         
        )}
        </main>
       </body>
    </html>
  );
}
